export const homeContent = {
  hero: {
    eyebrow: 'Mental Fellow',
    title: 'Not made',
    emphasis: 'to fit in.',
    action: 'Shop the collection',
    slides: [
      { src: '/uploads/model23.png', alt: 'A woman in a black ribbed crop top and jeans, with the words New Looks on a yellow and lilac background', wide: true },
      { src: '/uploads/model22.png', alt: 'A woman in a yellow cropped hoodie and black track pants, with the words Stay Real across the photo', wide: true },
      { src: '/uploads/model10.png', alt: 'A woman in a lime top and black jacket against a green wall', wide: true },
      { src: '/uploads/model24.png', alt: 'A woman in a red turtleneck and sunglasses holding a black woven bag' },
      { src: '/uploads/model2.png', alt: 'A woman in red holding a woven black bag by the handle' },
      { src: '/uploads/model5.png', alt: 'A woman in yellow holding a blue bag with a chain strap' },
      { src: '/uploads/model9.png', alt: 'A woman in a yellow top and pink sunglasses against a red shutter', wide: true },
      { src: '/uploads/model6.png', alt: 'A person in a lime hood and brown jacket carrying a red crossbody bag' },
    ],
    href: '/shop',
  },
  sale: {
    endsAt: '2026-10-04T18:29:59.000Z',
    href: '/sale',
  },
  doors: [
    {
      label: 'Shop women',
      href: '/women',
      image: '/uploads/model15.jpg',
      alt: 'A woman in a yellow cropped hoodie sitting in the sun',
    },
    {
      label: 'Shop men',
      href: '/men',
      image: '/uploads/model14.png',
      alt: 'A man in a black sleeveless top and sunglasses standing outside',
    },
  ],
  shopByMaterial: [
    {
      label: 'Travel',
      href: '/collections/travel',
      image: '/uploads/model15.jpg',
      alt: 'A woman in a yellow cropped hoodie',
    },
    {
      label: 'Office',
      href: '/collections/office',
      image: '/uploads/model16.jpg',
      alt: 'A woman in an orange suit holding her blazer open',
    },
    {
      label: 'Evening',
      href: '/collections/wedding',
      image: '/uploads/model9.png',
      alt: 'A woman in a yellow top and pink sunglasses',
    },
    {
      label: 'Premium',
      href: '/collections/premium',
      image: '/uploads/model5.png',
      alt: 'A woman in yellow holding a blue bag',
    },
  ],
  discover: {
    title: 'Discover',
    action: 'Shop new',
    href: '/new-arrivals',
    image: '/uploads/model16.jpg',
    alt: 'A woman in an orange suit holding her blazer open',
  },
  materialStory: {
    eyebrow: 'Material',
    title: 'Rice straw, made into leather.',
    body: 'Rice straw becomes leather. Wheat straw becomes suede. The finished sheet still has to work as a bag, a wallet, or a travel cube.',
    href: '/materials/paddy-rice-waste',
    action: 'See the leather',
    image: '/materials/rice-straw-leather.png',
    alt: 'A sheet of rice-straw leather beside a bundle of rice straw',
  },
  story: {
    eyebrow: 'Our story',
    title: 'Carry it. Wear it. Use it.',
    body: 'We do not stop at a material sample. The work is to turn that material into a product someone actually wants: a sling for the train, a belt that fits, a shoe that can be worn in.',
    image: '/uploads/model4.png',
    alt: 'Two women in red, one in a black cap and one in sunglasses',
  },
  materialNotes: [
    { icon: 'sprout', label: 'Rice straw leather' },
    { icon: 'wheat', label: 'Wheat straw suede' },
    { icon: 'tag', label: 'Named on every piece' },
    { icon: 'bag', label: 'Made to be used' },
  ],
}
