/**
 * Launch catalog until product tables are connected.
 * Photography is placeholder stock and must be replaced before a public launch.
 * Prices live here as seed data. Components never invent them.
 */

const ONE = ['One Size']
const BELT = ['80', '85', '90', '95', '100', '105']
const SHOE_M = ['UK 6', 'UK 7', 'UK 8', 'UK 9', 'UK 10', 'UK 11']
const SHOE_W = ['UK 3', 'UK 4', 'UK 5', 'UK 6', 'UK 7', 'UK 8']

function shot(src) {
  if (String(src).startsWith('/')) return [src, src]
  const base = `https://images.unsplash.com/${src}?auto=format&fit=crop&w=1000&h=1250&q=75`
  return [base, `${base}&crop=entropy`]
}

function slugPart(value) {
  return String(value)
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/(^-|-$)/g, '')
}

function product({ stock = {}, sizes, ...input }) {
  const variants = input.colors.flatMap((color) =>
    sizes.map((size) => ({
      id: `${input.slug}__${slugPart(color.name)}__${slugPart(size)}`,
      sku: `MF-${input.slug}-${slugPart(color.name)}-${slugPart(size)}`.toUpperCase(),
      color: color.name,
      size,
      stock: stock[`${color.name}-${size}`] ?? stock.default ?? 8,
      price: input.price,
      mrp: input.mrp,
    })),
  )
  return { ...input, variants }
}

function color(name, hex, id, alt) {
  return { name, hex, images: shot(id), alt }
}

const story = (summary, impact) => ({ summary, impact })

export const previewProducts = [
  product({
    id: 'paddy-sling',
    slug: 'paddy-sling',
    name: 'Paddy Sling',
    descriptor: 'Compact sling for a day out',
    description: 'A short sling with one main compartment and a zip pocket on the strap. The leather is made from rice straw.',
    gender: 'men',
    department: 'bags',
    productType: 'bag',
    category: 'sling-bags',
    material: 'paddy-rice-waste',
    collections: ['travel', 'gym'],
    care: 'Wipe with a dry cloth. Keep away from prolonged rain.',
    fitNote: 'Strap adjusts from 70 cm to 130 cm.',
    warranty: '12 months against manufacturing defects.',
    price: 2499,
    mrp: 2999,
    rating: 4.6,
    reviewCount: 48,
    flags: { new: true, bestseller: true, trending: true },
    taxNote: 'Inclusive of all taxes',
    createdAt: '2026-09-18',
    sizes: ONE,
    stock: { default: 12, 'Ink-One Size': 3 },
    attributes: {
      capacity: '7 L',
      dimensions: '28 × 16 × 8 cm',
      weight: '480 g',
      strapType: 'Adjustable webbing',
      closure: 'Zip',
      hardware: 'Brushed alloy',
      lining: 'Recycled textile',
      finish: 'Leather',
    },
    story: story(
      'Leather made from rice straw. The straw is the raw material; the grain you see is the leather.',
      'Measured impact figures are published only after a batch is verified.',
    ),
    colors: [
      color('Ink', '#1c1c1c', '/products/rice-leather-sling-ink.png', 'Black rice-straw leather sling'),
      color('Sand', '#c2b6a3', '/products/rice-leather-sling-sand.png', 'Sand rice-straw leather sling'),
    ],
  }),
  product({
    id: 'rice-brief',
    slug: 'rice-brief',
    name: 'Rice Brief',
    descriptor: 'Structured briefcase',
    description: 'A two-compartment brief with a padded laptop sleeve. Built for the office edit, with a handle and a detachable shoulder strap.',
    gender: 'men',
    department: 'bags',
    productType: 'bag',
    category: 'briefcases',
    material: 'recycled-textile',
    collections: ['office', 'laptop', 'premium'],
    care: 'Wipe clean. Do not machine wash.',
    fitNote: 'Fits a laptop up to 14 inches.',
    warranty: '12 months against manufacturing defects.',
    price: 6499,
    mrp: 7999,
    rating: 4.8,
    reviewCount: 31,
    flags: { new: false, bestseller: true, trending: false },
    taxNote: 'Inclusive of all taxes',
    createdAt: '2026-08-02',
    sizes: ONE,
    stock: { default: 6 },
    attributes: {
      capacity: '12 L',
      dimensions: '40 × 30 × 10 cm',
      weight: '980 g',
      strapType: 'Top handle and detachable strap',
      closure: 'Zip',
      hardware: 'Matte metal',
      lining: 'Recycled textile',
      finish: 'Fine grain',
    },
    story: story(
      'The body uses cloth rebuilt from textile waste. The laptop sleeve is padded and separate from the main compartment.',
      'Recycled textile content is recorded per batch. A percentage is shown only when that batch record is verified.',
    ),
    colors: [color('Charcoal', '#3a3a3a', 'photo-1548036328-c9fa89d128fa', 'Charcoal briefcase standing upright')],
  }),
  product({
    id: 'hemp-weekender',
    slug: 'hemp-weekender',
    name: 'Hemp Weekender',
    descriptor: 'Two-night travel bag',
    description: 'A soft weekender with a shoe pocket at one end and a strap that can sit on the shoulder or across the chest.',
    gender: 'men',
    department: 'bags',
    productType: 'bag',
    category: 'weekender-bags',
    material: 'hemp-fibre',
    collections: ['travel', 'premium'],
    care: 'Brush off dry dirt. Spot clean. Air outside the cupboard.',
    fitNote: 'Carry-on proportions. Check the airline if the flight is strict.',
    warranty: '12 months against manufacturing defects.',
    price: 7499,
    mrp: 8999,
    rating: 4.5,
    reviewCount: 22,
    flags: { new: true, bestseller: false, trending: true },
    taxNote: 'Inclusive of all taxes',
    createdAt: '2026-09-04',
    sizes: ONE,
    stock: { default: 5 },
    attributes: {
      capacity: '28 L',
      dimensions: '52 × 30 × 24 cm',
      weight: '1.1 kg',
      strapType: 'Shoulder strap',
      closure: 'Double zip',
      lining: 'Cotton',
      finish: 'Woven',
    },
    story: story(
      'The shell is a hemp-fibre cloth. Hemp is a crop fibre, not an agricultural-waste residue, and the product page says so.',
      'Impact numbers are left blank until a verified study exists for this construction.',
    ),
    colors: [color('Olive', '#5c6148', 'photo-1553062407-98eeb64c6a62', 'Olive weekender bag')],
  }),
  product({
    id: 'banana-tote',
    slug: 'banana-tote',
    name: 'Banana Tote',
    descriptor: 'Open tote for the working day',
    description: 'A structured tote with two handles and an interior pocket sized for a phone. The surface uses banana fibre from plants after the fruit harvest.',
    gender: 'women',
    department: 'bags',
    productType: 'bag',
    category: 'tote-bags',
    material: 'banana-fibre',
    collections: ['college', 'office'],
    care: 'Wipe with a barely damp cloth and dry flat.',
    fitNote: 'Sits on the shoulder. Not a backpack.',
    warranty: '12 months against manufacturing defects.',
    price: 3299,
    mrp: 3999,
    rating: 4.7,
    reviewCount: 64,
    flags: { new: true, bestseller: true, trending: true },
    taxNote: 'Inclusive of all taxes',
    createdAt: '2026-09-14',
    sizes: ONE,
    stock: { default: 10, 'Natural-One Size': 2 },
    attributes: {
      capacity: '14 L',
      dimensions: '38 × 30 × 14 cm',
      weight: '620 g',
      strapType: 'Twin handles',
      closure: 'Open top with magnetic snap',
      lining: 'Unlined pocket in recycled textile',
      finish: 'Natural fibre',
    },
    story: story(
      'Made using banana fibre taken from the plant after harvest.',
      'The material story names the source. It does not claim the finished bag has zero impact.',
    ),
    colors: [
      color('Natural', '#d8c7a6', 'photo-1590874103328-eac38a683ce7', 'Natural fibre tote bag'),
      color('Black', '#161616', 'photo-1584917865442-de89df76afd3', 'Black tote bag'),
    ],
  }),
  product({
    id: 'pineapple-envelope',
    slug: 'pineapple-envelope',
    name: 'Pineapple Envelope',
    descriptor: 'Evening envelope clutch',
    description: 'A flat envelope clutch with a hidden magnetic close. The face is a pineapple-leaf fibre sheet. This run is numbered and will not be repeated in this colour.',
    gender: 'women',
    department: 'bags',
    productType: 'bag',
    category: 'envelope-clutches',
    material: 'pineapple-fibre',
    collections: ['wedding', 'luxury', 'limited'],
    care: 'Store flat. Avoid perfume directly on the surface.',
    fitNote: 'Holds a phone, cards, and a lipstick. No strap.',
    warranty: '12 months against manufacturing defects.',
    price: 4599,
    mrp: 4599,
    rating: 4.9,
    reviewCount: 11,
    flags: { new: true, bestseller: false, trending: true },
    taxNote: 'Inclusive of all taxes',
    createdAt: '2026-09-20',
    sizes: ONE,
    stock: { default: 4 },
    attributes: {
      capacity: '1 L',
      dimensions: '26 × 14 × 3 cm',
      weight: '220 g',
      strapType: 'None',
      closure: 'Magnetic flap',
      finish: 'Fine leaf fibre',
    },
    story: story(
      'The face uses pineapple leaf fibre. Leaves are an agricultural by-product of the fruit harvest.',
      'This is a limited colour run. Availability is the stock count, not a scarcity slogan.',
    ),
    colors: [color('Ivory', '#efe6d6', 'photo-1566150905458-1bf1fc113f0d', 'Ivory envelope clutch')],
  }),
  product({
    id: 'bamboo-crossbody',
    slug: 'bamboo-crossbody',
    name: 'Bamboo Crossbody',
    descriptor: 'Everyday crossbody',
    description: 'A small crossbody with a front zip and an adjustable strap. The cloth is woven with bamboo fibre.',
    gender: 'women',
    department: 'bags',
    productType: 'bag',
    category: 'crossbody-bags',
    material: 'bamboo-fibre',
    collections: ['college'],
    care: 'Spot clean. Do not soak.',
    fitNote: 'Strap length 110–130 cm.',
    warranty: '12 months against manufacturing defects.',
    price: 2799,
    mrp: 3299,
    rating: 4.4,
    reviewCount: 19,
    flags: { new: false, bestseller: false, trending: true },
    taxNote: 'Inclusive of all taxes',
    createdAt: '2026-07-19',
    sizes: ONE,
    stock: { default: 9 },
    attributes: {
      capacity: '4 L',
      dimensions: '24 × 18 × 7 cm',
      weight: '390 g',
      strapType: 'Adjustable crossbody',
      closure: 'Zip',
      lining: 'Recycled textile',
    },
    story: story(
      'Bamboo fibre is a crop fibre used in the cloth. It is listed separately from waste-based materials.',
      'No carbon figure is printed until the construction has a verified assessment.',
    ),
    colors: [color('Moss', '#6d7058', 'photo-1591561954557-26941169b49e', 'Moss green crossbody bag')],
  }),
  product({
    id: 'cane-belt-bag',
    slug: 'cane-belt-bag',
    name: 'Cane Belt Bag',
    descriptor: 'Belt bag in bagasse sheet',
    description: 'A belt bag with a single zip compartment. The sheet uses sugarcane bagasse, the pulp left after the cane is pressed.',
    gender: 'women',
    department: 'bags',
    productType: 'bag',
    category: 'belt-bags',
    material: 'sugarcane-bagasse',
    collections: ['gym'],
    care: 'Wipe dry. Do not fold sharply along the same line.',
    fitNote: 'Belt adjusts from 70 cm to 110 cm.',
    warranty: '12 months against manufacturing defects.',
    price: 2799,
    mrp: 2799,
    rating: 4.3,
    reviewCount: 8,
    flags: { new: true, bestseller: false, trending: false },
    taxNote: 'Inclusive of all taxes',
    createdAt: '2026-09-08',
    sizes: ONE,
    stock: { default: 7 },
    attributes: {
      capacity: '2 L',
      dimensions: '22 × 14 × 6 cm',
      strapType: 'Adjustable belt',
      closure: 'Zip',
      finish: 'Matte',
    },
    story: story(
      'Made using a sheet derived from sugarcane bagasse.',
      'Bagasse is a processing residue. The product does not claim a zero-waste factory.',
    ),
    colors: [color('Clay', '#b08968', 'photo-1547949003-9792a18a2601', 'Clay coloured belt bag')],
  }),
  product({
    id: 'field-card-wallet',
    slug: 'field-card-wallet',
    name: 'Field Card Wallet',
    descriptor: 'Slim card wallet',
    description: 'Four card slots and a centre pocket for folded notes. The cover is the same rice-straw leather as the Paddy Sling. Initials can be added on request.',
    gender: 'men',
    department: 'wallets',
    productType: 'wallet',
    category: 'card-wallets',
    material: 'paddy-rice-waste',
    collections: ['corporate', 'custom'],
    care: 'Wipe clean. Do not soak.',
    warranty: '12 months against manufacturing defects.',
    price: 1499,
    mrp: 1999,
    rating: 4.5,
    reviewCount: 40,
    flags: { new: false, bestseller: true, trending: false },
    taxNote: 'Inclusive of all taxes',
    createdAt: '2026-06-11',
    sizes: ONE,
    stock: { default: 20 },
    attributes: {
      cardSlots: '4',
      cashCompartment: 'Centre pocket',
      coinCompartment: 'None',
      dimensions: '10.5 × 8 × 1 cm',
      closure: 'Open',
      features: ['Card slots', 'Cash compartment'],
    },
    story: story(
      'Leather cover made from rice straw, the same leather as the Paddy Sling.',
      'Personalisation is a studio service. It is separate from the material.',
    ),
    colors: [
      color('Ink', '#1c1c1c', '/products/rice-leather-wallet-ink.png', 'Black rice-straw leather card wallet'),
      color('Tan', '#a67c52', '/products/rice-leather-wallet-tan.png', 'Tan rice-straw leather card wallet'),
    ],
  }),
  product({
    id: 'continental-wallet',
    slug: 'continental-wallet',
    name: 'Continental Wallet',
    descriptor: 'Long wallet with a zip',
    description: 'A long wallet with a note compartment, eight card slots, and a zip coin pocket. The exterior uses banana fibre.',
    gender: 'women',
    department: 'wallets',
    productType: 'wallet',
    category: 'continental-wallets',
    material: 'banana-fibre',
    collections: ['premium'],
    care: 'Wipe clean. Empty the coin pocket before packing it away wet.',
    warranty: '12 months against manufacturing defects.',
    price: 3499,
    mrp: 3999,
    rating: 4.6,
    reviewCount: 27,
    flags: { new: false, bestseller: false, trending: true },
    taxNote: 'Inclusive of all taxes',
    createdAt: '2026-08-22',
    sizes: ONE,
    stock: { default: 8 },
    attributes: {
      cardSlots: '8',
      cashCompartment: 'Full note sleeve',
      coinCompartment: 'Zip pocket',
      dimensions: '19 × 10 × 2.5 cm',
      closure: 'Zip-around',
      features: ['Card slots', 'Cash compartment', 'Coin compartment'],
    },
    story: story(
      'Exterior made using banana fibre.',
      'The lining is a separate cloth and is named in the details, not folded into the fibre claim.',
    ),
    colors: [color('Natural', '#e6d3b3', 'photo-1627123424574-724758594e93', 'Natural long wallet')],
  }),
  product({
    id: 'passport-wallet',
    slug: 'passport-wallet',
    name: 'Passport Wallet',
    descriptor: 'Passport sleeve with cards',
    description: 'Holds one passport, two cards, and a folded boarding pass. The cover is leather made from rice straw.',
    gender: 'unisex',
    department: 'wallets',
    productType: 'wallet',
    category: 'passport-wallets',
    material: 'paddy-rice-waste',
    collections: ['travel', 'corporate'],
    care: 'Wipe clean.',
    warranty: '12 months against manufacturing defects.',
    price: 1799,
    mrp: 1799,
    rating: 4.4,
    reviewCount: 16,
    flags: { new: true, bestseller: false, trending: false },
    taxNote: 'Inclusive of all taxes',
    createdAt: '2026-09-01',
    sizes: ONE,
    stock: { default: 14 },
    attributes: {
      cardSlots: '2',
      cashCompartment: 'Ticket pocket',
      dimensions: '14 × 10.5 × 1 cm',
      closure: 'Open',
      features: ['Card slots'],
    },
    story: story(
      'Leather cover made from rice straw.',
      'Sized for a standard passport. It is not a travel wallet for cash and coins.',
    ),
    colors: [color('Ink', '#1a1a1a', '/products/rice-leather-wallet-ink.png', 'Black rice-straw leather passport wallet')],
  }),
  product({
    id: 'studio-key-pouch',
    slug: 'studio-key-pouch',
    name: 'Studio Key Pouch',
    descriptor: 'Zip pouch for keys',
    description: 'A small zip pouch so keys stay out of the lining of a bag. The material uses coconut husk residue.',
    gender: 'unisex',
    department: 'accessories',
    productType: 'accessory',
    category: 'key-pouches',
    material: 'coconut-waste',
    collections: ['corporate'],
    care: 'Wipe clean.',
    warranty: '6 months against manufacturing defects.',
    price: 999,
    mrp: 1299,
    rating: 4.2,
    reviewCount: 13,
    flags: { new: false, bestseller: false, trending: false },
    taxNote: 'Inclusive of all taxes',
    createdAt: '2026-05-03',
    sizes: ONE,
    stock: { default: 18 },
    attributes: {
      dimensions: '11 × 7 × 2 cm',
      closure: 'Zip',
      hardware: 'Alloy pull',
    },
    story: story(
      'Made using a material derived from coconut husk residue.',
      'A small product. The material source is named. No larger environmental total is claimed.',
    ),
    colors: [color('Stone', '#b7a99a', 'photo-1606760227091-3dd870d97f1d', 'Stone coloured key pouch')],
  }),
  product({
    id: 'luggage-tag',
    slug: 'luggage-tag',
    name: 'Luggage Tag',
    descriptor: 'Tag with a covered card',
    description: 'A luggage tag with a flap over the address card. Sold singly. The face is leather made from rice straw.',
    gender: 'unisex',
    department: 'accessories',
    productType: 'accessory',
    category: 'luggage-tags',
    material: 'paddy-rice-waste',
    collections: ['travel', 'corporate'],
    care: 'Wipe clean. Rewrite the card rather than soaking the tag.',
    price: 699,
    mrp: 699,
    rating: 4.1,
    reviewCount: 9,
    flags: { new: true, bestseller: false, trending: false },
    taxNote: 'Inclusive of all taxes',
    createdAt: '2026-09-11',
    sizes: ONE,
    stock: { default: 30 },
    attributes: {
      dimensions: '10 × 6 cm',
      closure: 'Strap and stud',
    },
    story: story(
      'Leather face made from rice straw.',
      'The strap is a separate component and is not the same leather.',
    ),
    colors: [color('Ink', '#222', '/products/rice-leather-tag.png', 'Black rice-straw leather luggage tag')],
  }),
  product({
    id: 'laptop-sleeve',
    slug: 'laptop-sleeve',
    name: 'Laptop Sleeve',
    descriptor: '14-inch sleeve',
    description: 'A padded sleeve for a 14-inch laptop. The exterior cloth is rebuilt from textile waste.',
    gender: 'unisex',
    department: 'accessories',
    productType: 'accessory',
    category: 'laptop-sleeves',
    material: 'recycled-textile',
    collections: ['laptop', 'college', 'office'],
    care: 'Spot clean. Do not wash the padding.',
    fitNote: 'Measure the laptop before ordering. 14-inch is the screen size, not the sleeve.',
    warranty: '12 months against manufacturing defects.',
    price: 2199,
    mrp: 2499,
    rating: 4.5,
    reviewCount: 21,
    flags: { new: false, bestseller: true, trending: false },
    taxNote: 'Inclusive of all taxes',
    createdAt: '2026-07-02',
    sizes: ONE,
    stock: { default: 11 },
    attributes: {
      dimensions: '36 × 26 × 2 cm',
      closure: 'Zip',
    },
    story: story(
      'Exterior made from recycled textile waste.',
      'The padding is a separate filling and is listed as such.',
    ),
    colors: [color('Graphite', '#4a4a4a', 'photo-1548036328-c9fa89d128fa', 'Graphite laptop sleeve')],
  }),
  product({
    id: 'route-organizer',
    slug: 'route-organizer',
    name: 'Route Organizer',
    descriptor: 'Packing cube set of two',
    description: 'Two packing cubes for a weekender. The suede is made from wheat straw. They compress flat when empty.',
    gender: 'unisex',
    department: 'travel',
    productType: 'travel',
    category: 'travel-organizers',
    material: 'wheat-waste',
    collections: ['travel'],
    care: 'Air after a trip. Spot clean.',
    warranty: '12 months against manufacturing defects.',
    price: 1899,
    mrp: 2299,
    rating: 4.3,
    reviewCount: 14,
    flags: { new: true, bestseller: false, trending: true },
    taxNote: 'Inclusive of all taxes',
    createdAt: '2026-09-16',
    sizes: ONE,
    stock: { default: 10 },
    attributes: {
      capacity: '6 L',
      dimensions: '30 × 20 × 10 cm and 24 × 16 × 8 cm',
      closure: 'Zip',
      finish: 'Suede',
    },
    story: story(
      'Suede made from wheat straw. The straw is the raw material; the nap is the finished suede.',
      'Sold as a pair. Capacity is the larger cube.',
    ),
    colors: [color('Straw', '#e0d2b0', '/products/wheat-suede-organizer.png', 'Wheat-straw suede packing cubes')],
  }),
  product({
    id: 'formal-belt',
    slug: 'formal-belt',
    name: 'Formal Belt',
    descriptor: '30 mm dress belt',
    description: 'A 30 mm belt with a rectangular buckle. The strap uses coconut-husk material with a smoother finish for tailored trousers.',
    gender: 'men',
    department: 'belts',
    productType: 'belt',
    category: 'formal-belts',
    material: 'coconut-waste',
    collections: ['office'],
    care: 'Wipe after wear. Do not bend the strap fully back on itself.',
    fitNote: 'The size is the strap length in centimetres, not your trouser size. Order one size up from your waist if you wear the belt on the hips.',
    chart: 'belts',
    warranty: '12 months against manufacturing defects.',
    price: 1999,
    mrp: 2499,
    rating: 4.4,
    reviewCount: 18,
    flags: { new: false, bestseller: false, trending: false },
    taxNote: 'Inclusive of all taxes',
    createdAt: '2026-04-18',
    sizes: BELT,
    stock: { default: 6, 'Black-100': 2 },
    attributes: {
      width: '30 mm',
      buckle: 'Rectangular alloy',
      dimensions: 'Sized by strap length',
    },
    story: story(
      'Strap made using a material derived from coconut husk.',
      'The buckle is metal and is not part of the husk material.',
    ),
    colors: [color('Black', '#111', 'photo-1523381210434-271e8be1f52b', 'Black belt strap in even light')],
  }),
  product({
    id: 'slim-belt',
    slug: 'slim-belt',
    name: 'Slim Belt',
    descriptor: '20 mm fashion belt',
    description: 'A narrow belt meant to sit on a dress or a high waist. The strap uses pineapple-leaf fibre.',
    gender: 'women',
    department: 'belts',
    productType: 'belt',
    category: 'slim-belts',
    material: 'pineapple-fibre',
    collections: ['wedding'],
    care: 'Wipe clean. Hang by the buckle, not folded in half.',
    fitNote: 'Size is strap length in centimetres.',
    chart: 'belts',
    warranty: '12 months against manufacturing defects.',
    price: 1799,
    mrp: 1799,
    rating: 4.2,
    reviewCount: 7,
    flags: { new: true, bestseller: false, trending: false },
    taxNote: 'Inclusive of all taxes',
    createdAt: '2026-09-06',
    sizes: BELT,
    stock: { default: 5 },
    attributes: {
      width: '20 mm',
      buckle: 'Small oval',
      dimensions: 'Sized by strap length',
    },
    story: story(
      'Strap made using pineapple leaf fibre.',
      'Width is 20 mm. It is a fashion belt, not a load-bearing work belt.',
    ),
    colors: [color('Ivory', '#f3efe6', 'photo-1523381210434-271e8be1f52b', 'Ivory belt strap folded once')]
  }),
  product({
    id: 'derby-shoe',
    slug: 'derby-shoe',
    name: 'Derby',
    descriptor: 'Open-lacing derby',
    description: 'An open-lacing derby with a recycled-textile upper and a stitched sole. The last is a standard UK fit.',
    gender: 'men',
    department: 'footwear',
    productType: 'shoe',
    category: 'derby-shoes',
    material: 'recycled-textile',
    collections: ['office', 'premium'],
    care: 'Brush dry dirt. Use a shoe tree. Do not machine wash.',
    fitNote: 'Standard width. If you are between UK sizes, take the larger one.',
    chart: 'shoes-men',
    warranty: '6 months against manufacturing defects. Soles wear with use and are not a defect.',
    price: 8999,
    mrp: 9999,
    rating: 4.6,
    reviewCount: 15,
    flags: { new: false, bestseller: true, trending: false },
    taxNote: 'Inclusive of all taxes',
    createdAt: '2026-03-12',
    sizes: SHOE_M,
    stock: { default: 4, 'Black-UK 11': 0, 'Black-UK 8': 2 },
    attributes: {
      upper: 'Recycled textile',
      sole: 'Rubber',
      closure: 'Lace',
      fit: 'Standard',
    },
    story: story(
      'The upper uses recycled textile waste. The sole is rubber and is named separately.',
      'Footwear wears down. Durability is not described as permanent.',
    ),
    colors: [color('Black', '#141414', 'photo-1533867617858-e7b97e060509', 'Black derby shoes')],
  }),
  product({
    id: 'hemp-chelsea',
    slug: 'hemp-chelsea',
    name: 'Hemp Chelsea',
    descriptor: 'Ankle chelsea boot',
    description: 'A chelsea boot with elastic side gussets. The upper cloth is hemp fibre. The sole is rubber.',
    gender: 'men',
    department: 'footwear',
    productType: 'shoe',
    category: 'chelsea-boots',
    material: 'hemp-fibre',
    collections: ['travel'],
    care: 'Brush and air. Stuff with paper if you do not own trees.',
    fitNote: 'UK sizing. The ankle opening is snug on purpose.',
    chart: 'shoes-men',
    warranty: '6 months against manufacturing defects.',
    price: 7499,
    mrp: 8499,
    rating: 4.5,
    reviewCount: 12,
    flags: { new: true, bestseller: false, trending: true },
    taxNote: 'Inclusive of all taxes',
    createdAt: '2026-08-28',
    sizes: SHOE_M,
    stock: { default: 4 },
    attributes: {
      upper: 'Hemp fibre',
      sole: 'Rubber',
      closure: 'Elastic gusset',
      fit: 'Standard',
    },
    story: story(
      'Upper made from hemp fibre. Hemp is a crop, and the page does not call it waste.',
      'The sole is a conventional rubber and is not included in the fibre description.',
    ),
    colors: [color('Tan', '#8d6a45', 'photo-1608256246200-53e635b5b65f', 'Tan chelsea boots')],
  }),
  product({
    id: 'banana-flat',
    slug: 'banana-flat',
    name: 'Banana Flat',
    descriptor: 'Round-toe ballet flat',
    description: 'A ballet flat with a thin sole and a round toe. The upper uses banana fibre backed with a textile.',
    gender: 'women',
    department: 'footwear',
    productType: 'shoe',
    category: 'ballet-flats',
    material: 'banana-fibre',
    collections: ['wedding'],
    care: 'Wipe the upper. Do not soak the sole edge.',
    fitNote: 'If you wear half sizes, take the next UK size up.',
    chart: 'shoes-women',
    warranty: '6 months against manufacturing defects.',
    price: 3499,
    mrp: 3999,
    rating: 4.3,
    reviewCount: 17,
    flags: { new: false, bestseller: false, trending: false },
    taxNote: 'Inclusive of all taxes',
    createdAt: '2026-06-30',
    sizes: SHOE_W,
    stock: { default: 5, 'Natural-UK 5': 1 },
    attributes: {
      upper: 'Banana fibre',
      sole: 'Leather-alternative sheet',
      closure: 'Slip-on',
      fit: 'Standard',
    },
    story: story(
      'Upper made using banana fibre.',
      'The sole is a different sheet and is listed on its own line.',
    ),
    colors: [color('Natural', '#eadcc4', 'photo-1543163521-1bf539c55dd2', 'Natural ballet flats')],
  }),
  product({
    id: 'platform-sneaker',
    slug: 'platform-sneaker',
    name: 'Platform Sneaker',
    descriptor: 'Low platform sneaker',
    description: 'A lace sneaker on a low platform. The upper is recycled textile. The sole uses recycled plastic where the batch allows, and the product says when it does not.',
    gender: 'women',
    department: 'footwear',
    productType: 'shoe',
    category: 'platform-sneakers',
    material: 'recycled-textile',
    collections: ['college'],
    care: 'Wipe the upper. Do not put textile sneakers in a washing machine.',
    fitNote: 'Runs standard. The platform adds height, not length.',
    chart: 'shoes-women',
    warranty: '6 months against manufacturing defects.',
    price: 4299,
    mrp: 4999,
    rating: 4.4,
    reviewCount: 23,
    flags: { new: true, bestseller: false, trending: true },
    taxNote: 'Inclusive of all taxes',
    createdAt: '2026-09-09',
    sizes: SHOE_W,
    stock: { default: 6 },
    attributes: {
      upper: 'Recycled textile',
      sole: 'Platform rubber',
      closure: 'Lace',
      fit: 'Standard',
    },
    story: story(
      'Upper made from recycled textile waste. The sole is rubber.',
      'Recycled plastic is not claimed for the sole unless a batch record says it is present.',
    ),
    colors: [
      color('White', '#f4f1ea', 'photo-1549298916-b41d501d3772', 'White platform sneakers'),
      color('Black', '#1b1b1b', 'photo-1542291026-7eec264c27ff', 'Black sneakers'),
    ],
  }),
]

export const previewReviews = {
  'paddy-sling': [
    {
      id: 'rev-sling-1',
      author: 'A. Mehra',
      rating: 5,
      title: 'Strap stays put',
      body: 'I wear it across the chest on the train. The zip does not creep open, and the ink colour does not show scuffs immediately.',
      image: '/uploads/model14.png',
      imageAlt: 'A man in a black sleeveless top',
      createdAt: '2026-08-12',
    },
  ],
  'banana-tote': [
    {
      id: 'rev-tote-1',
      author: 'N. Iyer',
      rating: 4,
      title: 'Holds a folder',
      body: 'Enough for a laptop sleeve and a bottle if you pack it upright. The natural colour marks if you lean it on a wet table.',
      image: '/uploads/model15.jpg',
      imageAlt: 'A woman in a yellow cropped hoodie',
      createdAt: '2026-09-02',
    },
  ],
  'pineapple-envelope': [
    {
      id: 'rev-envelope-1',
      author: 'S. Kapoor',
      rating: 5,
      title: 'Small enough for the evening',
      body: 'Phone, cards, and a lipstick. I did not miss a strap once I was out.',
      image: '/uploads/model9.png',
      imageAlt: 'A woman in a yellow top and pink sunglasses',
      createdAt: '2026-08-28',
    },
  ],
  'rice-brief': [
    {
      id: 'rev-brief-1',
      author: 'R. Das',
      rating: 4,
      title: 'Laptop has a place',
      body: 'A 14-inch laptop sits in its own compartment. I take it to the office, not for the weekend.',
      image: '/uploads/model16.jpg',
      imageAlt: 'A woman in an orange suit',
      createdAt: '2026-09-06',
    },
  ],
  'platform-sneaker': [
    {
      id: 'rev-sneaker-1',
      author: 'M. Shah',
      rating: 4,
      title: 'Usual size',
      body: 'My usual size. The platform adds height, and the length matches my other shoes.',
      image: '/uploads/model5.png',
      imageAlt: 'A woman in yellow holding a blue bag',
      createdAt: '2026-07-19',
    },
  ],
  'hemp-weekender': [
    {
      id: 'rev-weekender-1',
      author: 'K. Nair',
      rating: 5,
      title: 'Two nights',
      body: 'Two nights of clothes fit. I still checked the airline limit before the flight.',
      image: '/uploads/model6.png',
      imageAlt: 'A person in a lime hood carrying a red bag',
      createdAt: '2026-08-03',
    },
  ],
  'formal-belt': [
    {
      id: 'rev-belt-1',
      author: 'P. Joshi',
      rating: 5,
      title: 'Sits on the waist',
      body: 'I sized it by the strap length, not my trouser size. The 30 mm width sits cleanly on tailored trousers.',
      image: '/uploads/model17.png',
      imageAlt: 'A woman in a black top and jeans with a belt',
      createdAt: '2026-09-11',
    },
  ],
  'cane-belt-bag': [
    {
      id: 'rev-beltbag-1',
      author: 'L. Fernandes',
      rating: 4,
      title: 'Stays on the body',
      body: 'The belt adjusts, and the zip holds a phone and keys. I wear it when I do not want a bag on my shoulder.',
      image: '/uploads/model18.png',
      imageAlt: 'A woman in an orange top and shorts',
      createdAt: '2026-09-14',
    },
  ],
}
